import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import React from "react";
import { QueryProvider } from "@/app/providers/QueryProvider";
import StoreProviderState from "@/app/providers/StoreProvider";
import EntityNavigationLayout from "@/app/providers/EntityNavigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="bg-[#FC6736]">
      <body
        className={inter.className + "flex justify-items-center"}
        suppressHydrationWarning={true}
      >
        <QueryProvider>
          <StoreProviderState>
            <EntityNavigationLayout>{children}</EntityNavigationLayout>
          </StoreProviderState>
        </QueryProvider>
      </body>
    </html>
  );
}
