import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import React from "react";
import Link from "next/link";
import LinkElement from "./components/LinkElement";
import Navigation from "./components/Navigation";
import { QueryProvider } from "./providers/QueryProvider";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex justify-center">
        <div className="w-[630px] h-[453px] drop-shadow-md mt-2 flex flex-row border rounded-3xl overflow-hidden">
          <Navigation />
          <div className="bg-white">{children}</div>
        </div>
      </body>
    </html>
  );
}
